CREATE TABLE IF NOT EXISTS hoge (
    id BIGINT NOT NULL AUTO_RANDOM,
    name VARCHAR(255) NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
)
TTL = updated_at + INTERVAL 1 HOUR;
